[package]
name = "eco-pi"
version = "0.1.0"
edition = "2021"
authors = ["Tahar Meijs <tntmeijs@gmail.com>"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.10.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serialport = "4.3.0"
